# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 454de1fab82dab54c9c01c6b75e8c3a0892b3789c434aa4e14b15d8e51dd0f29bd2823bf8617e79680c1e6ea64d009cece1d77feaf635541069ae0c9075f5e77

test:
  secret_key_base: ee9aa40b2610d504747d0f9d7ad4e02906d2c464fe29fe64c6e4894862b6ccf43fb20a762e56e4d62e76d6dd470ff38a9263323812af35e1c6e8e37bd2a96ada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
